const eventActionTypes = {
  SAVE: "EVENT_SAVE",
  SAVE_SUCCEEDED: "EVENT_SAVE_SUCCEEDED",
  SAVE_FAILED: "EVENT_SAVE_FAILED",

  LOAD: "EVENT_LOAD",
  LOAD_SUCCEEDED: "EVENT_LOAD_SUCCEEDED",
  LOAD_FAILED: "EVENT_LOAD_FAILED",

  UPDATE: "EVENT_UPDATE",
  UPDATE_SUCCEEDED: "EVENT_UPDATE_SUCCEEDED",
  UPDATE_FAILED: "EVENT_UPDATE_FAILED",

  DELETE: "EVENT_DELETE",
  DELETE_SUCCEEDED: "EVENT_DELETE_SUCCEEDED",
  DELETE_FAILED: "EVENT_DELETE_FAILED",
};

export default eventActionTypes;
